# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7be0e9b212c6c3c100031906ff9b1fe924ce398145082b67a2fcc2c21abc39e3262cab5117cb413f0050fdd033ed8114e5e60f4de9a4b82a55aa5906bc0a2448

test:
  secret_key_base: fbde03193aee8ff55a5ad241e883c82529c51387a9befb762bd9792da9f17bfb4c787bf617ba197f18e48cb649da6fc10403d05ec655a22b470b3feac66f0316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
